### ISSUE TITLE
Video stream setting

### ISSUE THREAD

**Issue by farzadsw** [DroneEngage/droneengage_camera#2]
Hi,
Recently I tested the DroneEngage with multiple USB cameras. I can see the video stream on the WebClient and everything works OK.  However, I couldn't find any information regarding stream settings. 

Is it possible to set the video resolution and frame rate for the stream? 
Also, what is the streaming bitrate? Is it possible to configure the encoder?

**Comment by HefnySco** [comment]
Hi,
Glad to hear that it works well.
DE-Camera module works using Webrtc protocol the same protocol used in
massenger video chat. It automatically adapts resolution and frame rate
based on availability bandwidth. However we can still apply some settings
but it is fixed right now.
I plane to make a newer version end of this year with more features
regarding video control.
Thank you.
M. Hefny
